name: chat_gpt_eg
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  country_picker: ^2.0.19
  pinput: ^2.2.31
  rounded_loading_button: ^2.1.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  image_cropper: ^3.0.1
  uuid: ^3.0.7
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.13
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  speech_to_text: ^6.1.1
  lottie: ^2.3.0
  text_to_speech: ^0.2.3
  audioplayers: ^3.0.1
  grouped_list: ^5.1.2
  date_format: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
